### ISSUE TITLE
this should be a compound key

### ISSUE THREAD

**Issue by jasonseminara** [Teefmummy/Flashcard-App#1]
Your join tables should have a compound primary key. I believe the way you have it now makes TWO indexes; you want one. 
According to this thread, you could update your model https://stackoverflow.com/questions/41888549/how-to-implement-composite-primary-keys-in-rails

`add_index :instances, [:quiz_id, :user_id], unique: true`

https://github.com/Teefmummy/Flashcard-App/blob/84ee1535908bbfc8cbf754a41889a7d19acc3771/Flashcard-App/db/schema.rb#L31

**Comment by Teefmummy** [comment]
Thank you for this. 
Do you think I will have to do this for the Instances table as well as Answers?
